### ISSUE TITLE
null is not an object (evaluating UXCambridge.startWithKey)

### ISSUE THREAD

**Issue by vijay2330** [negativetwelve/react-native-ux-cam#106]
I am getting null is not an object (evaluating UXCambridge.startWithKey). Android is working perfectly but ios is showing this error. Any solution for this?

![Screenshot 2019-10-30 at 6 11 54 PM](https://user-images.githubusercontent.com/31308647/67859161-e29e1380-fb40-11e9-986c-e99131a38f59.png)

**Comment by madandrija** [comment]
I'm getting a similar result:

![image](https://user-images.githubusercontent.com/44572935/68872670-b072e100-06fe-11ea-8516-b088150bd4c5.png)

**Comment by feedcast-me** [comment]
Any fix here? I can’t use uxcam because of that

**Comment by rtanizawa** [comment]
I'm having a similar issue. Does anyone has a workaround?

**Comment by richardgroves** [comment]
Is this with react-native 0.60 or higher?

Due to changes in that version the setup process needs altering (we're in the process of updating our documentation - apologies for the delay but we've not had to split it out by platform and RN version before).


[ The issues are that we need you to manually run the pod install/update command now to load the RNUXCam into the project, and there is a version mismatch in our Pod (needs iOS >=10) and the default react-native Podfile which still supports iOS 9.0.]

So to start a new project with RN >= 0.60:

```
react-native init AwesomeProject
cd AwesomeProject
yarn add react-native-ux-cam
react-native link react-native-ux-cam

cd ios
```


Now you need to edit the `Podfile` to change the first line to be `platform :ios, '10.0'` rather than `platform :ios, '9.0'`

```
pod install
cd ..
```
Edit App.js to include your UXCam setup:
```
import RNUxcam from 'react-native-ux-cam';
RNUxcam.optIntoSchematicRecordings();
RNUxcam.startWithKey('YOUR API KEY');
```
and then, finally! :
```
react-native run-ios
```

(with a `react-native start` in another tab of course).

**Comment by madandrija** [comment]
> Is this with react-native 0.60 or higher?
> 

Yes, with the latest RN.

> Due to changes in that version the setup process needs altering (we're in the process of updating our documentation - apologies for the delay but we've not had to split it out by platform and RN version before).
> 
> [ The issues are that we need you to manually run the pod install/update command now to load the RNUXCam into the project, and there is a version mismatch in our Pod (needs iOS >=10) and the default react-native Podfile which still supports iOS 9.0.]
> 
> So to start a new project with RN >= 0.60:
> 
> ```
> react-native init AwesomeProject
> cd AwesomeProject
> yarn add react-native-ux-cam
> react-native link react-native-ux-cam
> 
> cd ios
> ```
> 
> Now you need to edit the `Podfile` to change the first line to be `platform :ios, '10.0'` rather than `platform :ios, '9.0'`
> 
> ```
> pod install
> cd ..
> ```
> 
> Edit App.js to include your UXCam setup:
> 
> ```
> import RNUxcam from 'react-native-ux-cam';
> RNUxcam.optIntoSchematicRecordings();
> RNUxcam.startWithKey('YOUR API KEY');
> ```
> 
> and then, finally! :
> 
> ```
> react-native run-ios
> ```
> 
> (with a `react-native start` in another tab of course).

Will try it out, tnx!

**Comment by madandrija** [comment]
> > Is this with react-native 0.60 or higher?
> 
> Yes, with the latest RN.
> 
> > Due to changes in that version the setup process needs altering (we're in the process of updating our documentation - apologies for the delay but we've not had to split it out by platform and RN version before).
> > [ The issues are that we need you to manually run the pod install/update command now to load the RNUXCam into the project, and there is a version mismatch in our Pod (needs iOS >=10) and the default react-native Podfile which still supports iOS 9.0.]
> > So to start a new project with RN >= 0.60:
> > ```
> > react-native init AwesomeProject
> > cd AwesomeProject
> > yarn add react-native-ux-cam
> > react-native link react-native-ux-cam
> > 
> > cd ios
> > ```
> > 
> > 
> > Now you need to edit the `Podfile` to change the first line to be `platform :ios, '10.0'` rather than `platform :ios, '9.0'`
> > ```
> > pod install
> > cd ..
> > ```
> > 
> > 
> > Edit App.js to include your UXCam setup:
> > ```
> > import RNUxcam from 'react-native-ux-cam';
> > RNUxcam.optIntoSchematicRecordings();
> > RNUxcam.startWithKey('YOUR API KEY');
> > ```
> > 
> > 
> > and then, finally! :
> > ```
> > react-native run-ios
> > ```
> > 
> > 
> > (with a `react-native start` in another tab of course).
> 
> Will try it out, tnx!

Tried it out,  had to run `cd ios/ && pod repo update && cd ..` and update iOS platform to 10 and now it's working, thanks!

**Comment by richardgroves** [comment]
Great! Glad that is working. I'm looking to see if we can drop the iOS version requirement back to 9 for simplicity, but I don't want anyone using the SDK to think it will actually work on iOS 9 so it is tricky. It just logs a message saying 'need iOS 10' and then does nothing more.
