### ISSUE TITLE
android not recording - com.uxcam.service.HttpPostService

### ISSUE THREAD

**Issue by nicoara** [negativetwelve/react-native-ux-cam#107]
After install, I am not able to get UXCam to record on Android.

The project builds fine, the app runs on the mobile phone, but UXCam makes no recording. 

There is no message regarding UXCam in the console log in Chrome for Remote Debugging. 

I have double checked and I am adding everything from here: https://help.uxcam.com/hc/en-us/articles/115000966691

system details.
 "react": "16.2.0",
"react-native": "0.54.4",
"react-native-ux-cam": "^5.1.11",

I found in AndroidManifest.xml the following line is red : 
<service android:name="com.uxcam.service.HttpPostService"/>
saying:
'unresolved class 'HttpPostService'

The application runs with or without this line, with no recording. 

The build.gradle is:
(I am running on an Android 8 ) 
```

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation files('libs/uxcam.jar')
}

```

Thank you

**Comment by triplumix** [comment]
I have the same issue RN 0.60

**Comment by safciplak** [comment]
> I have the same issue RN 0.60

mee to

**Comment by susanuxcam** [comment]
hey @safciplak, let's continue the discussion about this on the chat

**Comment by The0racle** [comment]
@susanuxcam can you please post any steps to fix this here? I'm having the same issue as I can't get my android app to record anything.

**Comment by nfranzmeier** [comment]
After seeing error messages in logcat regarding HttpPostService 
I found I was missing the HttpPostService from my AndroidManifest.xml file.
Here's a snippet from mine:
   
 <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true" android:usesCleartextTraffic="true">
        

        <service android:name="com.uxcam.service.HttpPostService"/>
