### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by bdombro** [negativetwelve/react-native-ux-cam#109]
Version: 5.1.11
React-Native: 0.61.1

```
$ pod install
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration
Detected React Native module pods for BVLinearGradient, RNAppAuth, RNDeviceInfo, RNFBAnalytics, RNFBApp, RNFBCrashlytics, RNFBDynamicLinks, RNFBRemoteConfig, RNGestureHandler, RNPermissions, RNReanimated, RNScreens, RNUxcam, RNVectorIcons, react-native-cameraroll, react-native-exif, react-native-photos-framework, and react-native-splash-screen
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RNUxcam":
  In Podfile:
    RNUxcam (from `../node_modules/react-native-ux-cam`)

Specs satisfying the `RNUxcam (from `../node_modules/react-native-ux-cam`)` dependency were found, but they required a higher minimum deployment target.
```

I'm not using UX Cam for IOS and don't understand this error, so I deleted your podspec file using patch-package, and that seems to allow pod install to pass.

**Comment by lukaskai** [comment]
in podfile set target to 10.0, that helps to overcome this particular issue. However, now I get such error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UXCam", referenced from:
      objc-class-ref in RNUxcam.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lukaskai** [comment]
I tried react-native-ux-cam@5.1.13-beta.2, but it did not help as well.

**Comment by richardgroves** [comment]
We've just published 5.1.13 without the beta tag, but other than some version number changes nothing else has changed.

I was able to make a new project and install the UXCam plugin and run it ok on iOS simulator - see attached terminal output (one glitch - my cocoapods repo cache was out of date, but the suggested fix worked).

[Terminal Saved Output.txt](https://github.com/negativetwelve/react-native-ux-cam/files/3901375/Terminal.Saved.Output.txt)

**Comment by lukaskai** [comment]
@richardgroves I managed to make it work, however, I had to add to RNUxcam.podspec a line s.static_framework = true, maybe you could add it to the package? As otherwise pod update does not work.

**Comment by richardgroves** [comment]
@lukaskai That's interesting - I've not needed that line when testing. It builds for simulator and device ok. What version of XCode are you using?

**Comment by lukaskai** [comment]
I am using latest version, however, in my podfile I have a line: "use_frameworks!"

**Comment by lukaskai** [comment]
@richardgroves will you add it? Because now on each npm install we have to go and manually add it.

**Comment by richardgroves** [comment]
@lukaskai Happy to make a change - but which one? 
`s.static_framework = true`

or 

`use_frameworks!`

[although I think the last one is for the final app Podfile rather than a podspec?]

**Comment by lukaskai** [comment]
@richardgroves you are correct. ux cam podspec should have s.static_framework = true added.

**Comment by richardgroves** [comment]
That change has been made and pushed to master on the repo. A proper release with it in will follow in the new year.

**Comment by matyj** [comment]
@richardgroves when will you release the new version? The above fix seems to be crucial..

**Comment by richardgroves** [comment]
Hi @matyj - version 5.1.14 was released a couple of hours ago. It has the change in it. Please let us know if it fixes problems you are having.

**Comment by matyj** [comment]
> Hi @matyj - version 5.1.14 was released a couple of hours ago. It has the change in it. Please let us know if it fixes problems you are having.

Sorry, I didn't catch it :) It seems like it works. ;)

**Comment by richardgroves** [comment]
@matyj No worries - not sure there is a reliable notification system for npm releases. Glad it works for you.

@lukaskai Can you check it is working for you too with the new version?
