### ISSUE TITLE
UXCam.optIntoSchematicRecordings(); 

### ISSUE THREAD

**Issue by NaeemCheema** [negativetwelve/react-native-ux-cam#115]
UXCam.optIntoSchematicRecordings();  is not a function 

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-10 at 14 09 14](https://user-images.githubusercontent.com/18673991/72140563-d7722a00-33b2-11ea-973d-522a0eaca17e.png)

"react-native-ux-cam": "^5.1.13",

**Comment by susanuxcam** [comment]
hey @NaeemCheema, can you send us a screenshot of your integration?

**Comment by NaeemCheema** [comment]
@susanuxcam
<img width="1440" alt="Screenshot 2020-01-10 at 10 51 52 PM" src="https://user-images.githubusercontent.com/18673991/72174543-cf8aa800-33fb-11ea-8651-6f02fda9943b.png">

**Comment by susanuxcam** [comment]
thanks @NaeemCheema, I've already sent it to our developers. I'll keep you updated!

**Comment by susanuxcam** [comment]
hey @NaeemCheema, could you try the most recent version 5.1.14 and let us know if it works?

**Comment by susanuxcam** [comment]
hey again @NaeemCheema, have you had a chance to test the most recent SDK version?

**Comment by susanuxcam** [comment]
Hey @NaeemCheema, I hope you're doing well! Could you please remove the screenshot with your appkey? We're asking for it because of privacy and safety reasons. Thanks!
