### ISSUE TITLE
UIWebView found by grep in UXCam/UXCam.framework/UXCam

### ISSUE THREAD

**Issue by matyj** [negativetwelve/react-native-ux-cam#117]
Hello, as said in the title, I had to search for some usages of UIWebView because of deprecation in Apple Store. It was found in the file mentioned in the title: is it possible, that it's somehow used in there?

**Comment by susanuxcam** [comment]
Hey @matyj, let me consult it with our engineers and let you know!

**Comment by matyj** [comment]
@susanuxcam thank you, I'm looking forward. it's crucial for us because you know, you never know what Apple will do in future. ;)

**Comment by matyj** [comment]
@susanuxcam any updates?

**Comment by susanuxcam** [comment]
Hey @matyj, our engineer who could work on it is currently on holiday so we should be able to come back to you next week. Apologies for the delay!

**Comment by richardgroves** [comment]
The next update of the SDK (expected to be 3.1.12) will remove the UIWebView references. Release expected before the middle of February.

**Comment by susanuxcam** [comment]
Hey @matyj! We've just released the 3.1.12 SDK which removes the UIWebView references. Please, test it out and let us know if it helps!

**Comment by richardgroves** [comment]
For now you can manually update the Pod to update to 3.1.12 native SDK, we'll make a full release of the react-native wrapper that depends on it shortly.

**Comment by jPaliwal88** [comment]
@richardgroves any timeline for this update

**Comment by richardgroves** [comment]
Hi - there is a new release just out that has the fix - 5.1.15 - see https://github.com/uxcam/react-native-ux-cam

**Comment by susanuxcam** [comment]
hey @jPaliwal88! If you update your SDK to the most recent version, it won't contain the UIWebView. I'm sorry for the late update on this!

**Comment by ZeerakHameem32** [comment]
I upgraded to lastest version i.e 5.1.15 and the issue is fixed. I tried u[dating everything and this updated ended up working for me. More info [here](https://github.com/react-native-community/react-native-webview/issues/819#issuecomment-596946722)
