### ISSUE TITLE
UXCAM causes second tap to be ignored that comes right after the first tap on any component like TouchableWithoutFeedback, TouchableOpacity, etc.

### ISSUE THREAD

**Issue by StarryFire** [negativetwelve/react-native-ux-cam#121]
We are on `react-native-ux-cam` v5.2.0 and this happens for both Android and iOS. 
If you continuously tap a button or anything that is tappable, the `onPress` event doesn't fire at all for every second press, third press, maybe for fourth it will if you give enough delay between the first and fourth.

This only happens when we enable UXCAM, otherwise our app works fine.
Any idea why is this happening? We are already on a paid plan and this is very disappointing.

**Comment by richardgroves** [comment]
Support for this is at https://github.com/uxcam/react-native-ux-cam where the latest version is published that has a work around for the React Native core problems causing this.
