### ISSUE TITLE
Swipe gesture breaking when using UXCam.startWithKey()

### ISSUE THREAD

**Issue by jakecronin** [negativetwelve/react-native-ux-cam#124]
### Versions: 
    "react-native": "0.63.4",
    "react-native-ux-cam": "^5.3.1",

### Problem
UXCam prematurely cancels touchable interaction.

Watching the API for this touchable component, when I do not have UXCam enabled, onTouchMove is called 20-30 times during my swipe gesture followed by a call to OnTouchEnd.

With UXCam enabled, onTouchMove is called 3-4 times before my swipeable component snaps back into place with no call to onTouchEnd. 

Any ideas as to the root cause of this problem? Has anyone found workarounds?

**Comment by richardgroves** [comment]
Please look at https://github.com/uxcam/react-native-ux-cam where the SDK is now maintained. For this issue there is a new method in the latest SDK that switches off the advanced gesture support in UXCam to allow the uncooperative code in the RN core to still work.
