### ISSUE TITLE
[iOS] No known class method for selector 'SetAutomaticScreenNameTagging:'

### ISSUE THREAD

**Issue by skleest** [negativetwelve/react-native-ux-cam#25]
Hello,

Getting this warning while building:
No known class method for selector 'SetAutomaticScreenNameTagging:'

UXCam: 2.5.7 (pod)
"react-native-ux-cam": "^2.2.0"
"react-native": "^0.39.2",
iOS only

Thanks!

**Comment by negativetwelve** [comment]
Oops, an upgrade to 2.5.8 should fix this issue, I'll do that right now!
