### ISSUE TITLE
[Android] undefined is not an object(evaluating 'RNUXCam.startWithKey')

### ISSUE THREAD

**Issue by ShadyXV** [negativetwelve/react-native-ux-cam#32]
![screenshot_20170405-190452 1](https://cloud.githubusercontent.com/assets/11807140/24707543/bc6673ce-1a33-11e7-83ce-b5ca613c5163.png)

**Comment by negativetwelve** [comment]
Hi there, what version of `react-native` and what version of `react-native-ux-cam` are you running? 

Can you add these lines somewhere in your code and send me the output?

```
import {NativeModules} from 'react-native';

console.log(NativeModules);
```

**Comment by ShadyXV** [comment]
hi i using react-native of version 0.41.2 and react-native-ux-cam version 3.0.0.
![image](https://cloud.githubusercontent.com/assets/11807140/24735684/d6c45c34-1aa3-11e7-9550-2049b22e3a91.png)
this is what i get by logging NativeModules. I can't find ux cam anywhere in here! is that the problem.

**Comment by ShadyXV** [comment]
hey @negativetwelve , i do think this issue is related to #30.I can't use any of the methods of UXCam because UXCam is undefined...

**Comment by ylac** [comment]
You may need to add `compile project(':react-native-ux-cam')` to your app/build.gradle under dependencies.

**Comment by negativetwelve** [comment]
hey there @ShadyXV, sorry for just now getting to this...

For me, I had to add the import:

```
import com.rnuxcam.rnuxcam.UXCamPackage;
```

to my Application.java file, then add:

```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          ...
          new UXCamPackage()
      );
    }
```

to add the package to the app. Let me know if those steps work for you, I'll update the readme if they do!

**Comment by Saumyadip-Pramanik** [comment]
Same issue, not getting method for ios or android.

**Comment by Subway19** [comment]
Getting this on iOS . any updates ?

**Comment by vijay2330** [comment]
@Subway19  any update regarding this? I am also getting issue in ios

**Comment by Subway19** [comment]
Didn't resolve this. We paused on UXCam for now. Will update here if
anything changes

Sumant Bagade

**Comment by Pasukaru** [comment]
Having a similar, but not the same issue.
For me the error is `TypeError: RNUXcam.startWithKey is not a function`. -> RNUxcam is defined, but it is an empty object.
On `"react-native": "0.61.4"` and `"react-native-ux-cam": "^5.1.11"`

**Comment by christiandave090697** [comment]
any fix for this? getting the same issue on android

**Comment by susanuxcam** [comment]
Hey everyone! Can you try using the SDK version 5.1.14? It should solve the issue!
