### ISSUE TITLE
Crashes Android App

### ISSUE THREAD

**Issue by ylac** [negativetwelve/react-native-ux-cam#34]
Hi, I've been trying to use this module but it keeps crashing with no error message on app start. I'm using react-native 0.43.3 and react-native-ux-cam 3.0.0.

I had to add "compile project(':react-native-ux-cam')" to the app/build.gradle to get it to register the package. Any ideas?

**Comment by negativetwelve** [comment]
Hi @ylac sorry to hear that. Did you try the solution posted here? https://github.com/negativetwelve/react-native-ux-cam/issues/33

If that works for you, I'll add a note to the readme about it.

**Comment by ylac** [comment]
Hi @negativetwelve, yep that fixed it for me, thanks a lot.
