### ISSUE TITLE
Can't use on Android

### ISSUE THREAD

**Issue by ylac** [negativetwelve/react-native-ux-cam#35]
Hi, I'm having issues trying to use the module. It builds fine but if I console.log(UXCam) in react-native after importing UXCam it returns {}.

Strangely, if I change UXCam.js to export the class UXCam instead of the instance "new UXCam()", console.log(UXCam) returns a function. If I try to instantiate it there, it also returns an empty object. Is there something going on with the class export? 

Also, I've noticed console.log(NativeModules) in react-native returns an empty object, but console.log(NativeModules.RNUXCam) returns [object object] in UXCam.js, if that helps.

**Comment by negativetwelve** [comment]
hey there @ylac, sorry for just now getting to this...

For me, I had to add the import:

```
import com.rnuxcam.rnuxcam.UXCamPackage;
```

to my Application.java file, then add:

```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          ...
          new UXCamPackage()
      );
    }
```

to add the package to the app. Let me know if those steps work for you, I'll update the readme if they do!
