### ISSUE TITLE
No Date Received

### ISSUE THREAD

**Issue by willlaserlike** [negativetwelve/react-native-ux-cam#38]
Hello, 

I followed the instructions and add UXCam.startWithKey('my-key') to index.app.js. The app runs successfully on both android and ios devices.  But I am still stuck on the integration page since it say no data received. 

How can I debug this issue?

**Comment by negativetwelve** [comment]
Hi @willlaserlike thanks for writing in. Are you saying there's a problem with UXCam itself? It's probably best to contact them directly via the support widget in the bottom right corner of the screen. This package is only concerned with the react-native integration with UXCam, not UXCam itself. Hope they can help you with your issue!

**Comment by willlaserlike** [comment]
I see the recordings after 1 hour. So there's no issue now. Thanks for the great library!

**Comment by richardgroves** [comment]
Hi @willlaserlike - it should appear much sooner than that (within a couple of minutes is normal - although a long (>10 minutes say) session could take a little longer to process. Let us know if it continues to take a long time for sessions to show up for you.

**Comment by safciplak** [comment]
can't see any data from android and ios freezing please help

**Comment by susanuxcam** [comment]
hey @safciplak, we're already talking about this on the chat so please let's continue our discussion there
