### ISSUE TITLE
Virtual Memory Hogger on Recording over Video Components. 

### ISSUE THREAD

**Issue by wookelvin** [negativetwelve/react-native-ux-cam#45]
There's a big issue with virtual memory usage when a video is playing. 
As a video is being recorded on a big screen, the memory usage shoots through the roof exceeding beyond 1400 MB if a full screen video is playing beyond 5 minutes. 

The app will close unexpectingly and the logs report that the app has 
'exceeded mem limit: ActiveHard 1400 MB'.

**Comment by negativetwelve** [comment]
cc @richardgroves - a UXCam employee that can hopefully help you with this issue. Your best bet would be to contact support. This looks like a native issue (this package is developed by me as a 3rd party and it's also just a small bridge between react-native and the actual native library)

**Comment by negativetwelve** [comment]
Going to close this as it's an issue with the native library and not the react-native wrapper. You can definitely continue discussion via this issue if you'd like!

**Comment by richardgroves** [comment]
@wookelvin Can you open a support issue for this at UXCam.com please so we can work through the problem and find a solution. Please reference this thread and me so it gets immediately to me.

Thanks,
Richard
