### ISSUE TITLE
[Android] No data from Android

### ISSUE THREAD

**Issue by fliPmitKlammern** [negativetwelve/react-native-ux-cam#47]
Hello there,

I have integrated react-native-ux-cam as described in the docs and while it works perfectly on iOS, there seems to be a problem with Android: The project is building and running just fine, however there is no data appearing in UXCam. I can call UXCam functions without errors, but calling UXCam.urlForCurrentSession() just gives 'null/s/null'.

I am using React Native 0.51 with React Native Navigation. Does anyone have an idea how to solve this issue?

**Comment by negativetwelve** [comment]
cc @aouaki who implemented the android portion

@fliPmitKlammern are you able to collect recordings using the native UXCam library? https://uxcam.com/docs#android

**Comment by fliPmitKlammern** [comment]
@negativetwelve Thanks for your rapid response! By integrating the native library and calling UXCam.startWithKey() in my MainActivity I am now able to collect recordings. Calling UXCam.urlForCurrentSession() in JavaScript now also works as expected, as well as all the screens tagged in JavaScript. So for now it seems this issue has been solved. Might have been a problem related to how React Native Navigation is handling Activities in contrast to plain React Native?

**Comment by negativetwelve** [comment]
It could be, but I'm not 100% positive. If you find that there is a fix we can apply to the react-native module, I will gladly accept it. It could indeed be the way that the navigation library is using activities (I handle all routing in plain JS).

**Comment by ACCTFORGH** [comment]
I am having the same issue here. Is it required to call startWithKey from Java code?

**Comment by Damnum** [comment]
Same issue here. In Java code it works, with react-native-ux-com, data are not sent.

In iOS it works as expected.

**Comment by The0racle** [comment]
Am I missing something? I can't make it to work at all. Tried RN installation steps, nothing; tried android native steps (gradle), nothing. Can somebody help?
