### ISSUE TITLE
[iOS] Can build on new RN

### ISSUE THREAD

**Issue by tobob** [negativetwelve/react-native-ux-cam#48]
ReactNative: 0.53.3

```
/Users/wojciechbozek/folder/some/node_modules/react-native-ux-cam/ios/RNUXCam.h:10:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by negativetwelve** [comment]
Hi @tobob, would you like to submit a PR to fix this issue? Would gladly appreciate it!

**Comment by tobob** [comment]
sure, I will try to fix this :)

**Comment by tobob** [comment]
I think that is related with Pods @negativetwelve 

I did `react-native link react-native-ux-cam`, then I changed Podfile and add   `pod "UXCam", "~> 2.5.12"`
however `pod 'react-native-ux-cam', :path => '../node_modules/react-native-ux-cam'` was there also
I after installation react-native-ux-cam appear inside `Developers Pods` and then start madness, because from this location it is not able to Resolve React

what I do to resolve issue:
- remove `pod 'react-native-ux-cam', :path => '../node_modules/react-native-ux-cam'` from Podfile and rebuild Pods
- inside *MainApp/Libraries* I add `RNUXCam.xcodeproj` I found in `node_modules/react-native-ux-cam/ios`
- then I use drag/drop `RNUXCam.xcodeproj/Products/libRNUXCam.a ` into *Build Phases* -> *Link binary with libraries*

@negativetwelve my resolution works for me, however I don't know how to fix *react-native link* or *Pods* in this case

**Comment by negativetwelve** [comment]
Interesting, do you want to try updating the version here https://github.com/negativetwelve/react-native-ux-cam/blob/master/react-native-ux-cam.podspec#L17 and then building the pod within your app? That will cause it to use a later version of UXCam

**Comment by MaheshNandam** [comment]
build failed due to 'UXCam/UXCam.h' file not found,

@negativetwelve, any idea about this?

**Comment by negativetwelve** [comment]
Hi @MaheshNandam let's continue the conversation in #51

**Comment by fearmear** [comment]
Hey, you're supposed to add Pods directory `$(SRCROOT)/Pods/Headers/Public` to HEADER_SEARCH_PATHS [here](https://github.com/negativetwelve/react-native-ux-cam/blob/master/ios/RNUXCam.xcodeproj/project.pbxproj#L216) and [here](https://github.com/negativetwelve/react-native-ux-cam/blob/aa9f9aa9b66b7c4eb11753d1c07f34322a0ea430/ios/RNUXCam.xcodeproj/project.pbxproj#L237) to make it compatible with Pod setup.
