### ISSUE TITLE
[iOS] build failed due to 'libRNUXCam.a' and 'UXCam/UXCam.h' file not found 

### ISSUE THREAD

**Issue by MaheshNandam** [negativetwelve/react-native-ux-cam#51]
My Package:

		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-ux-cam": "^4.4.0",

<img width="1191" alt="screen shot 2018-04-03 at 6 11 16 pm" src="https://user-images.githubusercontent.com/13198616/38249958-0d6f1f46-376b-11e8-88cc-a1bc0dd63169.png">

<img width="1181" alt="screen shot 2018-04-03 at 6 14 45 pm" src="https://user-images.githubusercontent.com/13198616/38249982-20213642-376b-11e8-8ef4-d46e445591ee.png">

I have added 'RNUXCam.xcodeproj' under libraries and added 'libRNUXCam' under link binary with libraries, but didn't get 'LibRNUXCam.a' file under libraries as mentioned in the image [?]

@negativetwelve or @aouaki or @Asaf-S, can you help me to fix this issue?

**Comment by negativetwelve** [comment]
Hi @MaheshNandam have you installed the `pod` following the instructions in the README? https://github.com/negativetwelve/react-native-ux-cam#ios-with-react-native-and-cocoapods

**Comment by MaheshNandam** [comment]
Hey @negativetwelve,

Yes!, I have done pod installation successfully, but after I got 'Argument list too long: recursive header expansion failed at react-native-ux-cam', 

<img width="1212" alt="screen shot 2018-04-04 at 6 10 56 pm" src="https://user-images.githubusercontent.com/13198616/38308113-aca2de4a-3833-11e8-8660-980a4c0e8478.png">

Along with that After installing react-native-ux-cam, I have both 'pod "UXCam"' and 'pod "react-native-ux-cam", :path => '../node_modules/react-native-ux-cam'' in pod file,

<img width="1229" alt="screen shot 2018-04-04 at 6 12 43 pm" src="https://user-images.githubusercontent.com/13198616/38308159-d5412802-3833-11e8-9bf7-2e7323c25fe7.png">

can you guide me to deal this issue?

**Comment by negativetwelve** [comment]
Hmm if you click on RNUXCam.xcodeproj under the Libraries directory. Can you find where the paths are set (it should be under something like Build Settings). Try removing the relative path that is listed there.

Sorry I don't have any screenshots or anything, hope this helps!

**Comment by MaheshNandam** [comment]
@negativetwelve, Can you tell me what exactly I have to remove from the below-mentioned paths,


<img width="1179" alt="screen shot 2018-04-05 at 12 04 03 pm" src="https://user-images.githubusercontent.com/13198616/38350609-a2b6e250-38c9-11e8-9758-5906c87b37e0.png">


<img width="1185" alt="screen shot 2018-04-05 at 12 04 29 pm" src="https://user-images.githubusercontent.com/13198616/38350602-999c91b0-38c9-11e8-978c-9682f2a2fab2.png">

**Comment by negativetwelve** [comment]
from the top screenshot, you can remove the `ios/Pods` and the `clients/ios` paths. the second one should be okay. clean the app and then re-compile everything and let me know if you get any other errors

**Comment by MaheshNandam** [comment]
After clean, got this issue "argument list too long: recursive header at react-native-camera"

**Comment by negativetwelve** [comment]
Can you add back the `${SRCROOT}/../../../ios/Pods` path and:

1. make sure the `/../../../` is correctly pointing to your iOS directory
2. If it is, try adding the specific name of the pod, `ios/Pods/UXCam` to the list so that it only looks for that module

**Comment by MaheshNandam** [comment]
Yes!, along with that I have added '  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'' to podFile

nonetheless, after the build, I get the below error,

<img width="1440" alt="screen shot 2018-04-05 at 2 33 32 pm" src="https://user-images.githubusercontent.com/13198616/38356886-b1b568de-38de-11e8-9efb-d47fc3a84898.png">

**Comment by negativetwelve** [comment]
hmm I'm not sure anymore 😢 

This issue seems to be present on other react-native modules, do you want to try things listed in this thread? https://github.com/invertase/react-native-firebase/issues/294

**Comment by MaheshNandam** [comment]
RCTComponent.h error is solved,

but still i have argument list too long at $(SRCROOT)/../../../ios/Pods/react-native-camera issue!.

**Comment by negativetwelve** [comment]
can you screenshot your RNUXCam.xcodeproj build settings again? ?just want to double check

**Comment by MaheshNandam** [comment]
Sure,

 <img width="1177" alt="screen shot 2018-04-05 at 3 16 51 pm" src="https://user-images.githubusercontent.com/13198616/38358996-99689ac0-38e4-11e8-8cb5-cbca7aa6c14f.png">

**Comment by MaheshNandam** [comment]
@negativetwelve, 

Adding pods to the relative paths is working fine, Thanks a lot! 👍

**Comment by negativetwelve** [comment]
great! glad it finally worked out! Going to close this issue since we solved your issue 😄
