### ISSUE TITLE
[iOS] Duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by MaheshNandam** [negativetwelve/react-native-ux-cam#52]
Issue:

build failed due to the following files!

/Users/...Build/Products/Debug-iphoneos/react-native-ux-cam/libreact-native-ux-cam.a(RNUXCam.o)
/Users/.../Build/Products/Debug-iphoneos/libRNUXCam.a(RNUXCam.o)

And also, do we need to have both pod->react-native-ux-cam and pod->uxcam pod lines at pod file?

@negativetwelve

**Comment by negativetwelve** [comment]
Hi @MaheshNandam is this after a recent update? You should only need UXCam in your podfile, not react-native-ux-cam (since you're linking using `react-native link`)

**Comment by MaheshNandam** [comment]
Yeah, 

I got fixed the issue by removing the react-native-ux-cam from Pod target files.

Thanks, @negativetwelve.

**Comment by negativetwelve** [comment]
👍 no problem!
