### ISSUE TITLE
[Android] Could not find com.uxcam:uxcam:2.5.8.

### ISSUE THREAD

**Issue by MaheshNandam** [negativetwelve/react-native-ux-cam#53]
Hey @negativetwelve,

Failed to resolve ' com.uxcam:uxcam:2.5.8', anyidea?

**Comment by negativetwelve** [comment]
Did you follow the instructions [here](https://github.com/negativetwelve/react-native-ux-cam#android)?

**Comment by MaheshNandam** [comment]
Yes!, I Did, but still!!

**Comment by negativetwelve** [comment]
Can you screenshot your `build.gradle` file?

**Comment by MaheshNandam** [comment]
Hey @negativetwelve,

Downgrading react-native-camera to 0.12.0, and closing 'Android studio' and opened again, it works for me.

**Comment by negativetwelve** [comment]
sounds good! glad you solved it 👍
