### ISSUE TITLE
[iOS] pod install error: transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by davidmessem** [negativetwelve/react-native-ux-cam#56]
I am following the instructions to install on iOS, and get to the `pod install` step, but get the following error

`[!] The 'Pods-<project>' target has transitive dependencies that include static binaries: (<path>/ios/Pods/UXCam/UXCam.framework)`

Here is my full Podfile

```
target '<project>' do
  use_frameworks!

  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Auth', '~> 4.13.0'
  pod 'Firebase/Database', '~> 4.13.0'
  
  pod 'react-native-ux-cam', :path => '../node_modules/react-native-ux-cam'
  pod "UXCam", "~> 2.5.12"

  target '<project>Tests' do
    inherit! :search_paths
  end

end
```

**Comment by richardgroves** [comment]
Hi @davidmessem ,

Could you try adding the line:

```use_frameworks!```

at the top of the podfile and see if that fixes it.

2.5.12 is also a rather old version - 2.5.17 is preferred which the ~ might get but I'm not sure.

**Comment by davidmessem** [comment]
I have just tried 2.5.17, and still get the error. Here is cocoapods output:

```
Analyzing dependencies
Fetching podspec for `react-native-ux-cam` from `../node_modules/react-native-ux-cam`
Downloading dependencies
Installing Firebase (4.13.0)
Installing FirebaseAnalytics (4.2.0)
Installing FirebaseAuth (4.6.1)
Installing FirebaseCore (4.0.20)
Installing FirebaseDatabase (4.1.5)
Installing FirebaseInstanceID (2.0.10)
Installing GTMSessionFetcher (1.1.15)
Installing GoogleToolboxForMac (2.1.4)
Installing UXCam (2.5.17)
Installing leveldb-library (1.20)
Installing nanopb (0.3.8)
Installing react-native-ux-cam (4.4.0)
[!] The 'Pods-Aspira' target has transitive dependencies that include static binaries: (<path>/ios/Pods/UXCam/UXCam.framework)
```

**Comment by richardgroves** [comment]
Ah - Ok...

Can you try taking the 

```pod "UXCam", "~> 2.5.17"```

out - I think that including React-native-uxcam pod is including UXCam already, and then the direct reference is duplicating the framework.

I'm mobile at the moment, so am not able to test the podfile directly. If this doesn't work I'll stop guessing and wait until I can run it myself.

**Comment by davidmessem** [comment]
I'm afraid that didn't work

Podfile
```
platform :ios, '9.0'

target '<project>' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for <project>
  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Auth', '~> 4.13.0'
  pod 'Firebase/Database', '~> 4.13.0'

  pod 'react-native-ux-cam', :path => '../node_modules/react-native-ux-cam'

  target '<project>Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Cocoapods output
```
Update all pods
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `react-native-ux-cam` from `../node_modules/react-native-ux-cam`
Downloading dependencies
Installing Firebase (4.13.0)
Installing FirebaseAnalytics (4.2.0)
Installing FirebaseAuth (4.6.1)
Installing FirebaseCore (4.0.20)
Installing FirebaseDatabase (4.1.5)
Installing FirebaseInstanceID (2.0.10)
Installing GTMSessionFetcher (1.1.15)
Installing GoogleToolboxForMac (2.1.4)
Installing UXCam (2.5.17)
Installing leveldb-library (1.20)
Installing nanopb (0.3.8)
Installing react-native-ux-cam (4.4.0)
[!] The 'Pods-<project>' target has transitive dependencies that include static binaries: (<path>/ios/Pods/UXCam/UXCam.framework)
```

**Comment by davidmessem** [comment]
As a workaround, I have taken `pod 'react-native-ux-cam', :path => '../node_modules/react-native-ux-cam'` out and left `pod "UXCam", "~> 2.5.17"` in the Podfile, and added react-native-ux-cam manually to the project. 

But that does not solve this issue.

**Comment by richardgroves** [comment]
Hi,

Firstly glad you have found a workaround!

Secondly in a turn around from my first response above can you try **removing** "the use_frameworks!" line from the PodFile - after having a podfile of just react-native-ux-cam on a native iOS project that reproduced your issue taking away the use_frameworks! did allow 'pod install' to complete (and the code builds + runs).

**Comment by richardgroves** [comment]
Closing this as the latest update includes the UXCam SDK directly without using cocoapods.
