### ISSUE TITLE
UXCam.startWithKey is not a function

### ISSUE THREAD

**Issue by dverma4u** [negativetwelve/react-native-ux-cam#62]
getting error UXCam.startWithKey is not function

i have done all steps mentioned in documentation

1) npm i react-native-ux-cam
2) react-native link react-native-ux-cam
3) added pod "UXCam", "~> 2.5.12" in Podfile
4) pod install

**Comment by malcolm-s** [comment]
I'm having this issue as well - everything is working fine on Android though?

Output from pods
```
Installing UXCam (2.5.18)
Installing react-native-ux-cam (4.5.0)
```

**Comment by malcolm-s** [comment]
Yep still having that issue here on iOS - @dverma4u @negativetwelve any idea on how to fix it?

**Comment by dverma4u** [comment]
@malcolm-s   @yjose  yes actually the documentation is not updated i think.

to resolve this error we need both manual and automatic installations

firstly install uxcam via cocoapod , and then add RNUXCam.xcodeproj from ./node_modules/react-native-uxcam
also add libRNUXCam.a from products into Build Phases -> Link Binaries With Libraries
