### ISSUE TITLE
UXCam missing sensitive fields hide

### ISSUE THREAD

**Issue by ionatower** [negativetwelve/react-native-ux-cam#63]
Hi, 

It seems like the react native hide all sensitive fields option is not implemented as a function?

UXCam.occludeAllTextFields(boolean occludeAll);

Found here:
https://help.uxcam.com/hc/en-us/articles/115000967031-Hide-Sensitive-Views

**Comment by negativetwelve** [comment]
Hi @ionatower feel free to submit a PR to add the missing methods to the SDK and I'll publish a new version.

**Comment by richardgroves** [comment]
hi @ionatower The methods for hiding specific views are now in the newly released wrapper for UXCam SDK 3.0.X which is in this repo master branch now and published on npm as version 5.0.0
