### ISSUE TITLE
[IOS] Expo detached : Cannot build => #import 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by Nico924** [negativetwelve/react-native-ux-cam#65]
My project is a detached expo project with the latest expo & react native version and this react-native-ux-cam plugin linked to it.

Here is my config
Computer:
- Mac OS 10.13.6
- node v8.11.2
- npm 6.4.1
- Xcode 10.0 

npm packages:
"expo": "^30.0.0",
"expokit": "^1.7.1",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
[...]
"react-native-ux-cam": "^4.5.0",
[...]

Podfile:
basic detached podfile +

pod 'react-native-ux-cam', :path => '../node_modules/react-native-ux-cam'  

pod "UXCam", "~> 2.5.12"

When doing pod install
I got
Installing UXCam (2.5.**18**)
...
Installing react-native-ux-cam (4.5.0)
...

The project is building well without the react-native-ux-cam link however once I add the two lines above and I do the pod install. I always get  a **Build Failed** with:

'React/RCTBridgeModule.h' file not found

I tried to remove the React part as suggested in some issues I found in stackOverflow or github but without any success.

Do you have any other suggestion ?

**Comment by negativetwelve** [comment]
Hi @Nico924, thanks for the detailed report. Unfortunately, this module hasn't been updated for recent versions of react-native so that might be causing some issues here.

Which version of Expo and React Native are you using?

**Comment by Nico924** [comment]
Hello @negativetwelve,

I am using **expo 30.0.0** and the associated react-native version (https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz)  which correspond to **react-native 0.55.4**

However, I retried renaming <React/RCTBridgeModule.h> to "RCTBridgeModule.h" and then another import having the same structure (<React/... .h> to "... .h") (I cannot remember the name of the second one) and the build worked and also the creation of an archive. I even could see some recordings 👌 I did that without really knowing what I was doing so maybe you have an idea why it worked ? 

A final detail, I saw that, since there is UXCam, the app is a bit slower, is it a common behaviour ? 

Thank you in advance for your answer.

**Comment by negativetwelve** [comment]
No problem @Nico924, thanks for posting your solution. My best bet is that some of the imports have changed since this module was last updated.

I actually don't work on UXCam, I'm just the creator of the react-native module for it 😄 For UXCam general questions, you should reach out to their team.

cc @richardgroves

**Comment by richardgroves** [comment]
Hi @Nico924 - can you raise a support issue at UXCam.com with the slowdown issue you are seeing - reference my name and this thread so it gets routed properly.
