### ISSUE TITLE
Update to version 3.0

### ISSUE THREAD

**Issue by Titozzz** [negativetwelve/react-native-ux-cam#67]
Hello, UXCam just released a new major version (3.0) with a new dashboard. Are you planning to update or do I have to submit a PR / build my own wrapper 😄 ?

**Comment by indapublic** [comment]
@Titozzz It would be wonderful

**Comment by richardgroves** [comment]
Hi - we are working on an updated wrapper to more directly integrate with v3 SDK - you can see a preview here - https://github.com/uxcam/react-native-ux-cam/tree/v3.0.0 - and over the next couple of weeks we hope to work with @negativetwelve and the community on this project to test and integrate it here.

**Comment by richardgroves** [comment]
Hi @Titozzz - the UXCam v3.0.X SDK wrapper has now been put in this repo and published to npm.
