### ISSUE TITLE
I can't install react-native-ux-cam by cocoaPods

### ISSUE THREAD

**Issue by cj768025549** [negativetwelve/react-native-ux-cam#75]
![default](https://user-images.githubusercontent.com/3918091/51891588-8bfd8080-23da-11e9-9261-4bdf1f39c240.png)
I don't want to install react-native-ux-cam by draging RNUxcam.xcodeproj file inside node_module/react-native-ux-cam/ios to your project on Libraries group on Xcode. That will cause something wrong on CircleCI.
So I rather install react-native-ux-cam by CocoaPods, but RNUxcam.podspec is missing something.

**Comment by kleyos** [comment]
> No podspec found for `react-native-ux-cam` in `../node_modules/react-native-ux-cam`

**Comment by nikhiysham** [comment]
It look's like the podspec has an error.  s.homepage was empty and s.source was point to the wrong url. 

Change RNUxcam.podspec file in ios folder as below: 

```
Pod::Spec.new do |s|
  s.name         = "RNUxcam"
  s.version      = "1.0.0"
  s.summary      = "RNUxcam"
  s.description  = <<-DESC
                  RNUxcam
                   DESC
  s.homepage     = "https://github.com/negativetwelve/react-native-ux-cam/blob/master/README.md"
  s.license      = "MIT"
  # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "author" => "author@domain.cn" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/negativetwelve/react-native-ux-cam.git", :tag => "master" }
  s.source_files  = "RNUxcam/**/*.{h,m}"
  s.requires_arc = true


  s.dependency "React"
  #s.dependency "others"
end
```

and then in your project Podfile :

`pod 'RNUxcam', path: "../node_modules/react-native-ux-cam", :podspec => "../node_modules/react-native-ux-cam/ios/RNUxcam.podspec"`

**Comment by anniewey** [comment]
Is there any other workaround rather than changing the files manually in `node_modules`? The error will still occur when we run it remotely using CI

**Comment by nikhiysham** [comment]
@anniewey you can fork the github repo and edit it as you like.

**Comment by samernady** [comment]
any update on this I am getting 
[!] No podspec found for `react-native-ux-cam` in `../node_modules/react-native-ux-cam`

**Comment by richardgroves** [comment]
@madandrija Thanks for you input. What I'm not understanding is how to get react-native > 0.60 to automagically add the `pod 'RNUXCam' ...` line to the PodFile - it seems to still need the `react-native link react-native-ux-cam` to add that in, and then a `cd ios && pod update && cd ..` to get it to actually install the UXCam SDK framework.

From the comments omitted during the `react-native link react-native-ux-cam` it appears that stage shouldn't be needed - but I can't find any documentation on how to adjust our setup to make it happen with just `yarn add react-native-ux-cam`

**Comment by madandrija** [comment]
> @madandrija Thanks for you input. What I'm not understanding is how to get react-native > 0.60 to automagically add the `pod 'RNUXCam' ...` line to the PodFile - it seems to still need the `react-native link react-native-ux-cam` to add that in, and then a `cd ios && pod update && cd ..` to get it to actually install the UXCam SDK framework.
> 
> From the comments omitted during the `react-native link react-native-ux-cam` it appears that stage shouldn't be needed - but I can't find any documentation on how to adjust our setup to make it happen with just `yarn add react-native-ux-cam`

Your issue seems to be with understanding how RN >= 0.60 linking works. In short, just `yarn add ...` or `npm install ...` is not enough AND the "automatic" in "automatic linking in RN > 0.60" refers to you not needing to add further changes in your `MainApplication.java` or `AppDelegate.m`, and most of the time I still do need to run the link command.

In any case,  [install instructions for ux-cam](https://github.com/negativetwelve/react-native-ux-cam#installation) explicitly list these steps so they aren't skippable

**Comment by richardgroves** [comment]
I still think that somehow it can be made that the `yarn add ...` is enough - but the 'docs' at https://github.com/react-native-community/cli/blob/master/docs/autolinking.md don't give me a clear example of how to change the UXCam repo to support it automatically adding our Pod line into the project pod.

>> In any case, install instructions for ux-cam explicitly list these steps so they aren't skippable
I know - I wrote those - but I want to make them shorter and remove the extra steps that the 0.60 'autolinking' appears to offer....

**Comment by madandrija** [comment]
> I still think that somehow it can be made that the `yarn add ...` is enough - but the 'docs' at https://github.com/react-native-community/cli/blob/master/docs/autolinking.md don't give me a clear example of how to change the UXCam repo to support it automatically adding our Pod line into the project pod.
> 
> I know - I wrote those - but I want to make them shorter and remove the extra steps that the 0.60 'autolinking' appears to offer....

Sorry, didn't notice while writing my response.

Now that I understand what you are actually asking 😄I can tell you that I also do not fully understand the "how", but what I did understand is if you support `autolinking`, then there won't be an entry in the `Podfile`, and looking at what we are using, [Sentry](https://github.com/getsentry/sentry-react-native) - perhaps you can check their code/contact them?

**Comment by madandrija** [comment]
@richardgroves - [found it](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#what-do-i-need-to-have-in-my-package-to-make-it-work)

**Comment by attitude** [comment]
I had a bit trouble understanding the problem, so I'm leaving here my note for the others.

This repository has last tag for version [5.1.9](https://github.com/negativetwelve/react-native-ux-cam/blob/5.1.9/uxcam-react-wrapper/RNUxcam.podspec). Trying to install version above that fails just due to Pod trying to checkout non-existing branch. I had to run `pod spec lint ./node_modules/react-native-ux-cam/RNUxcam.podspec` to see why the _podspec_ is failing:

```
warning: Could not find remote branch 5.1.11 to clone.
fatal: Remote branch 5.1.11 not found in upstream origin
```

Tag links below are missing for already published NPM versions:

* ✅ [NPM @ 5.1.9](https://www.npmjs.com/package/react-native-ux-cam/v/5.1.9) ~ ✅ [Github @ 5.1.10](https://github.com/negativetwelve/react-native-ux-cam/blob/5.1.9/uxcam-react-wrapper/RNUxcam.podspec)
* ✅ [NPM @ 5.1.10](https://www.npmjs.com/package/react-native-ux-cam/v/5.1.10) ~ ⚠️ [Github @ 5.1.10](https://github.com/negativetwelve/react-native-ux-cam/blob/5.1.10/uxcam-react-wrapper/RNUxcam.podspec)
* ✅ [NPM @ 5.1.11](https://www.npmjs.com/package/react-native-ux-cam/v/5.1.11) ~ ⚠️ [Github @ 5.1.11](https://github.com/negativetwelve/react-native-ux-cam/blob/5.1.11/uxcam-react-wrapper/RNUxcam.podspec)

**Comment by richardgroves** [comment]
@attitude Sorry about the missing tags. I didn't realise that they were relied on during the install process. Nothing in the `npm publish` process indicates an issue.

I've added the appropriate tags now and will update our release process so they aren't missed in the future.

**Comment by attitude** [comment]
@richardgroves 🙏 thanks for adding the 10 and 11 patch version tags. (Will edit my comment above to reflect changes.)

Also is wonder if there a reason not to add the missing 8 patch version tag too?

**Comment by richardgroves** [comment]
> Also is wonder if there a reason not to add the missing 8 patch version tag too?
I have to dig back and find which commit was that version? ;-) But here it is - https://github.com/negativetwelve/react-native-ux-cam/tree/5.1.8

I'm still seeing problems with the `pod spec lint` though:

```
richard$ pod spec lint ./node_modules/react-native-ux-cam/RNUxcam.podspec

 -> RNUxcam (5.1.10)
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - WARN  | [iOS] license: Unable to find a license file
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 1 warning.

[!] React has been deprecated
```
Any ideas?

**Comment by attitude** [comment]
✅  I managed to upgrade from 5.1.7 to 5.1.8 with no issues.

⚠️  Upgrading to 5.1.9 failed first due *[!] CocoaPods could not find compatible versions for pod "UXCam"*. Updating dependency from iOS 9.0 to 10.0 and running `pod install --repo-update` && `pod update UXCam` was required to run to fix the issue.

✅  Upgrading to 5.1.10 works as expected.
✅  Upgrading to 5.1.10 works as expected.

Based on [this comment on a similar looking issue](https://github.com/CocoaPods/CocoaPods/issues/6357#issuecomment-269705571) I think (not sure if I understand it correctly) the linting problem might be that the `RNUxcam.podspec` file not being in the root of this GitHub repository. Just a guess.

Hope it helps to investigate possible issue with the lint.

**Comment by richardgroves** [comment]
Thanks for the update @attitude 

It's all well and good for CocoaPods to want the PodSpec in the root of the repo but that doesn't really work when there are other platforms not using Pods and the example code to sit alongside. I'll try and check with some other modules too see if/how they get around this.

**Comment by saeedtkh** [comment]
I have the same issue on react native 60.5. Any updates?

**Comment by saeedtkh** [comment]
Well, I could fixed it by upgrading the platform :ios to '10.0' in my pod file.

**Comment by richardgroves** [comment]
@saeedtkh Ah yes - that would fix it. Our UXCam native SDK podspec says iOS10 now but I think the default React native podspec is iOS9 which means there is likely to be a refusal to integrate our SDK until the base SDK is updated.

Not sure who is still able to test for iOS9 so I'd consider it dangerous to build something new with that low a base level. Our SDK will actually run on iOS9, it just fails out (safely) early on without being able to do anything useful.

**Comment by madandrija** [comment]
I solved all UXCam installation problems by:

1. "upgrading the platform :ios to '10.0' in my pod file."
2. Running `cd ios/ && pod repo update && cd ..`
