### ISSUE TITLE
Android gradle update

### ISSUE THREAD

**Issue by crobinson42** [negativetwelve/react-native-ux-cam#77]
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-ux-cam
```

![screenshot 2019-02-19 11 05 55](https://user-images.githubusercontent.com/5973579/53040489-588c9f80-3436-11e9-92f9-2d7e0104bc4c.png)

**Comment by crobinson42** [comment]
@negativetwelve are you up for this fix? It's a blocker for anyone wanting to use the latest version or react-native.

**Comment by uxcam-com** [comment]
@crobinson42 Thanks for the suggestion, we will quickly make the change and push it to the repo.

**Comment by richardgroves** [comment]
Hi @crobinson42 - the fix for this has been merged to master now. Can you let us know if it fixes your problem?

Thanks,
Richard

**Comment by crobinson42** [comment]
Thanks - that appears to do the trick.

Until this is released, the workaround is to add this to your project `../android/build.gradle`

```
allprojects {

    subprojects {
        afterEvaluate {
            project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion = 28
                        buildToolsVersion = "28.0.3"
                    }
                }
        }
    }
...
}
```
