### ISSUE TITLE
function logEvent, logEventWithProperties not working

### ISSUE THREAD

**Issue by cereme** [negativetwelve/react-native-ux-cam#82]
There is UXCam's official document of function logEvent, logEventWithProperties :
https://help.uxcam.com/hc/en-us/articles/115000969072-Log-Events-and-Properties
![image](https://user-images.githubusercontent.com/19284878/59272531-2f1bac00-8c91-11e9-9b20-84176718bc8b.png)

so I applied : 
(though the document says "UXCam.logEvent~", I think RNUxcam is right: Using UXCam makes "undefined: UXCam" error)

```javascript
    RNUxcam.logEventWithProperties('hotVideoClicked', {link})
```

then I meet the error screen:
![Screenshot_1560256642](https://user-images.githubusercontent.com/19284878/59272501-21662680-8c91-11e9-919b-d3f79416d378.png)

I saw PR(https://github.com/negativetwelve/react-native-ux-cam/pull/61).
Is the official document containing misinformation?

**Comment by richardgroves** [comment]
Hi,

Sorry about the problems you are encountering.

Could you try just using logEvent with two parameters:

```
RNUxcam.logEvent(eventName, properties)
```

so 

```
RNUxcam.logEvent('hotVideoClicked', {link})
```

as I think we've replaced the two methods (with and without properties) with one that can handle both cases. I'll get the documentation looked at if this works ok for you.

Richard

**Comment by cereme** [comment]
> RNUxcam.logEvent(eventName, properties)

It works! Thanks.
