### ISSUE TITLE
occludeAllTextView vs. occludeAllTextFields

### ISSUE THREAD

**Issue by matthewng** [negativetwelve/react-native-ux-cam#83]
In react-native, `static occludeAllTextView()` calls `UXCamBridge.occludeAllTextFields()`.

On iOS, the method is `occludeAllTextFields` with a boolean parameter.
On Android, the method is `occludeAllTextView` with no parameters.

**Comment by susanuxcam** [comment]
Hey @matthewng, I'm sorry about coming back to you so late. Do you still experience this issue? Do you want us to dig deeper into it?
