### ISSUE TITLE
Fail to import in typescript project

### ISSUE THREAD

**Issue by vinco-mobile** [negativetwelve/react-native-ux-cam#90]
Hi,
I'm need import your library from typescript ? I try append @types definition but not found

| => npm install @types/react-native-ux-cam
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-native-ux-cam - Not found
npm ERR! 404

How I can import your library in typescript ?

Best regards

**Comment by susanuxcam** [comment]
Hey @vinco-mobile, I'm sorry about coming back to you so late. Do you still experience this issue? Do you want us to dig deeper into it?
