### ISSUE TITLE
Android tagScreenName not working

### ISSUE THREAD

**Issue by antpuleo2586** [negativetwelve/react-native-ux-cam#98]
Hi,

I've implemented this library but for some reason, on Android only, the correct screen names aren't appearing in the recordings. I always get `MainActivity` and if I `setAutomaticScreenNameTagging(false)`, I just get `unknown` as the screen name.

This works on iOS.

React native v0.60.4.
React navigation v3.11.1

Any help would be appreciated, thanks!

**Comment by theanilpaudel** [comment]
Hi @antpuleo2586 ,
Can you update the library to latest version i.e 5.1.9 and try again.

**Comment by antpuleo2586** [comment]
Hi @theanilpaudel 

I've updated but I'm actually now getting dependency issues on iOS.

```
[!] CocoaPods could not find compatible versions for pod "UXCam":
  In Podfile:
    RNUxcam (from `../node_modules/react-native-ux-cam`) was resolved to 5.1.9, which depends on
      UXCam (~> 3.1.6)

Specs satisfying the `UXCam (~> 3.1.6)` dependency were found, but they required a higher minimum deployment target.
```

Nevertheless, on Android I still have the same problem, however, it's only the initial call which isn't working.

My code is:

```
RNUxcam.startWithKey('xxxxxxxxx');
RNUxcam.optIntoSchematicRecordings();
RNUxcam.tagScreenName('Home');
```

Subsequent calls to `tagScreenName` work, but this initial one doesn't.

If I add a `setTimeout`, and give it 5 seconds, it works though, but this is far from ideal.

i.e.

```
RNUxcam.startWithKey('xxxxxxxxx');
RNUxcam.optIntoSchematicRecordings();
setTimeout(() => RNUxcam.tagScreenName('Home'), 5000);
```

Is there any way to set this initial screen along with the `startWithKey` call? Or await a promise to set the screen once the library has finished initialising?

Thanks!

**Comment by theanilpaudel** [comment]
@antpuleo2586 
Can you try updating the iOS version, UXCam support `ios > 10` 

On Android can you try this

```
RNUxcam.startWithKey(‘xxxxxxxxx’);
RNUxcam.optIntoSchematicRecordings();
RNUxcam.setAutomaticScreenNameTagging(false);
RNUxcam.tagScreenName(‘Home’);

**Comment by richardgroves** [comment]
A new version of the package (5.1.10) has been released which fixes the mismatch in iOS version requirement between the RNUXCam podspec file and the UXCam iOS SDK. iOS10 is the minimum version supported.
